Weiss gripper
personalrobotics/herb_description pull request #53
Opened 2018-10-29 01:16 UTC by Kaiden898

Changes were made to incorporate the Weiss gripper.

Summary of Changes Made:
1) urdf and srdf xacro files added for Weiss gripper, as well as standalone xacro files
2) added files mentioned in 1 to CMakeLists.txt to generate appropriate urdf and srdf files
3) modified the CmakeLists.txt, herb.urdf.xacro and herb.srdf.xacro to allow selection of Weiss gripper
4) added a launch file in order to directly load and view the robot model for testing purposes

2018-10-29 19:34 UTC, brianhou requested changes
Thanks for the PR! I left some suggested changes, but the big one is to rename `weiss_fmf` to `wsg50` throughout. We can add arguments to the appropriate macro if we decide we need to support other fingers.

2018-10-29 19:34 UTC, brianhou commented on CMakeLists.txt
> +  if(${hand_option} STREQUAL "weiss_fmf")
Instead of `weiss_fmf`, let's just call this `wsg50`. If we find that it's necessary to have different fingers than the FMF (e.g. Patrick's), I think we can handle that with an additional flag.

2018-10-29 19:34 UTC, brianhou commented on CMakeLists.txt
> +set(WEISS_STANDALONE_URDF_XACRO "${ROBOTS_SRC_DIR}/weiss_fmf_standalone.urdf.xacro")
Instead of `WEISS_*` and `weiss_fmf*`, let's have `WSG50_*` and `wsg50*`.

2018-10-29 19:34 UTC, brianhou commented on CMakeLists.txt
I think we should also add `WAM_WSG50_STANDALONE*`.

2018-10-29 19:34 UTC, brianhou commented on CMakeLists.txt
> +set(HERB_HAND_OPTIONS "bh280" "bh282" "weiss_fmf" "no")
`weiss_fmf` -> `wsg50`

2018-10-29 19:34 UTC, brianhou commented on CMakeLists.txt
> +set(FULL_HERB_URDF_ARGS "left_weiss_fmf:=true" "right_weiss_fmf:=true")
I'm not sure exactly what our "default" configuration will be in the future, but let's keep the BarrettHands as the default for now and undo this change.

2018-10-29 19:34 UTC, brianhou commented on CMakeLists.txt
>    ${HERB_URDF}
We should also add `WAM_WSG50_STANDALONE_URDF` here.

2018-10-29 19:34 UTC, brianhou commented on CMakeLists.txt
> -install(DIRECTORY DESTINATION "${CATKIN_PACKAGE_SHARE_DESTINATION}/robots")
Why were these changes necessary? I think we should revert these.

2018-10-29 19:34 UTC, brianhou commented on README_wsg-50_addition.md
> +## Instructions For WSG-50 Simulation Setup
I think this file is unnecessary.

2018-10-29 19:34 UTC, brianhou commented on launch/herb_Weiss.launch
> +<launch>
I think this file is unnecessary, since this repository is just for the actual URDFs and SRDFs.

2018-10-29 19:34 UTC, brianhou commented on rviz/herb_weiss.rviz
> +Panels:
Same as the launch file above -- I think this file is unnecessary, since this repository is just for the actual URDFs and SRDFs.

2018-10-29 19:34 UTC, brianhou commented on robots/herb.srdf.xacro
> +  <xacro:macro name="weiss" params="prefix:=${prefix}">
`weiss` -> `weiss_endeffector` to match the other macro names.

2018-10-29 19:34 UTC, brianhou commented on robots/herb.srdf.xacro
> +
Nit: delete this extra line.

2018-10-29 19:34 UTC, brianhou commented on robots/herb.srdf.xacro
> +
Nit: delete this extra line.

2018-10-29 19:34 UTC, brianhou commented on robots/herb.srdf.xacro
> +  <xacro:arg name="left_none" default="false"/>
Let's delete the `*_none` arguments and do some xacro logic below to infer when to use `xacro:empty_endeffector`.

2018-10-29 19:34 UTC, brianhou commented on robots/herb.srdf.xacro
> +  <xacro:arg name="left_none" default="false"/>
Actually, maybe we can do something like https://github.com/ros/xacro/issues/191#issuecomment-427333003.

2018-10-29 19:34 UTC, brianhou commented on robots/herb.srdf.xacro
> +    <xacro:barretthand_endeffector prefix="right" perception="$(arg left_perception)"/>
Typo: `left_perception` -> `right_perception`?

2018-10-29 19:34 UTC, brianhou commented on robots/herb.srdf.xacro
> +    <xacro:weiss prefix="left"/>
Typo: `left` -> `right`?

2018-11-02 20:01 UTC, brianhou requested changes
Almost there! I think we just need to delete a few unnecessary files and clean up a couple nits.

2018-11-02 20:01 UTC, brianhou commented on CMakeLists.txt
> +build_xacro(${WSG50_STANDALONE_URDF_XACRO} ${WSG50_STANDALONE_URDF} "")
Let's move these two `WSG50_STANDALONE`s up to merge them with the `BH*_STANDALONE`s.

2018-11-02 20:01 UTC, brianhou commented on CMakeLists.txt
> +  "left_wsg50:=false" "right_wsg50:=false")
I think these should already be set to false by default, so it's not necessary to set them here.

2018-11-02 20:01 UTC, brianhou commented on CMakeLists.txt
> +set(FULL_HERB_SRDF_ARGS "left_barrett:=true" "right_barrett:=true"
Same as above (but I think we should keep `right_perception:=true`).

2018-11-02 20:01 UTC, brianhou commented on CMakeLists.txt
> +  ${WSG50_FMF_STANDALONE_URDF}
I think these should be `WSG50_STANDALONE_*` instead.

2018-11-02 20:01 UTC, brianhou commented on CMakeLists.txt
> -install(DIRECTORY DESTINATION "${CATKIN_PACKAGE_SHARE_DESTINATION}/robots")
I still think these changes should be reverted?

2018-11-02 20:01 UTC, brianhou commented on README_wsg-50_addition.md
> +## Instructions For WSG-50 Simulation Setup
I still think these should be deleted.

2018-11-02 20:01 UTC, brianhou commented on launch/herb_view.launch
> +<launch>
I think this should be deleted, since this repo is just for urdfs/srdfs.

2018-11-02 20:01 UTC, brianhou commented on robots/wsg50_standalone.srdf.xacro
> +
Should there be a `<xacro:wsg50/>` here as well?

2018-11-02 20:01 UTC, brianhou commented on robots/wam_wsg50_standalone.urdf.xacro
> +        <!-- The force/torque sensor is 12 mm thick. -->
Let's add a TODO to have the correct measurements from @hanjuns.

2018-11-02 20:01 UTC, brianhou commented on robots/wsg50.urdf.xacro
> +  <!-- GRIPPER LEFT -->
Nit: left gripper?

2018-11-02 20:01 UTC, brianhou commented on robots/wsg50.urdf.xacro
> +   <!-- GRIPPER right -->
Nit: inconsistent capitalization

2018-11-02 20:01 UTC, brianhou commented on rviz/herb_view.rviz
> +Panels:
I think this should be deleted, since this repo is just for urdfs/srdfs.

2018-11-02 20:01 UTC, brianhou commented on robots/wsg50.urdf.xacro
> +    <!-- right FINGER -->
Nit: inconsistent capitalization

2018-11-02 20:03 UTC, brianhou commented on robots/herb.srdf.xacro
> +  <xacro:macro name="wsg50" params="prefix:=${prefix}">
`wsg50` -> `wsg50_endeffector` to match the other macro names.

2018-11-02 21:38 UTC, Kaiden898 commented on CMakeLists.txt
> +  "left_wsg50:=false" "right_wsg50:=false")
correct they are set to false by default. I have them there as place holders so no one has to look up the variable name but I guess variable names are pretty straight forward. So should I just delete all variables that are set to false and only have the necessary default variables set to true?

2018-11-02 22:31 UTC, brianhou commented on CMakeLists.txt
> +  "left_wsg50:=false" "right_wsg50:=false")
Yep!

2018-11-02 22:32 UTC, Kaiden898 commented on robots/wsg50.urdf.xacro
> +  <!-- GRIPPER LEFT -->
I am not sure why I named the left/right part the finger attaches to as left/right gripper. I can go through and rename them as left/right finger_mount to make it more clear as well.

2018-11-03 16:51 UTC, brianhou approved these changes

2018-11-03 16:59 UTC, brianhou commented
Looks great, thanks for the changes!

2018-11-03 16:59 UTC, merged